version: '3.8'

services:

  frontend:
    build: ./frontend
    container_name: thriftcloud_frontend
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: thriftcloud_backend
    depends_on:
      - postgres

  worker:
    build: ./worker
    container_name: thriftcloud_worker
    depends_on:
      - backend

  postgres:
    image: postgres:15
    container_name: thriftcloud_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: thriftcloud
    ports:
      - "5432:5432"

  nginx:
    build: ./nginx
    container_name: thriftcloud_nginx
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend